import {
  ServiceCategory,
  ServiceItem,
  ProviderProfile,
  Booking,
  BookingStatus,
  PaymentMethod,
  PaymentStatus,
  MeasurementProfile,
  TailoringOrder,
  TailoringStage,
  CaregiverProfile,
  CarePlan,
  RentalListing,
  RentalType,
  EmergencyListing,
  EmergencyServiceType,
  BusinessProfile,
  ProductItem,
} from '@parasheba/types';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api/v1';

export const MOCK_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat-home',
    slug: 'home-services',
    name: 'Home Services',
    nameBn: 'বাসাবাড়ির সেবা',
    description: 'Electricians, plumbers, AC technicians, cleaners, painters & carpentry.',
    iconName: 'Wrench',
    group: 'home',
    servicesCount: 18,
  },
  {
    id: 'cat-personal',
    slug: 'personal-family',
    name: 'Personal & Family',
    nameBn: 'ব্যক্তিগত ও পারিবারিক',
    description: 'Home tutors, caregivers, babysitting, beauty parlour & salon at home.',
    iconName: 'HeartHandshake',
    group: 'personal',
    servicesCount: 14,
  },
  {
    id: 'cat-karigor',
    slug: 'karigor',
    name: 'Karigor Tailoring',
    nameBn: 'কারিগর দর্জি সেবা',
    description: 'Doorstep custom tailoring, measurement visits, panjabi, suit & alteration.',
    iconName: 'Scissors',
    group: 'personal',
    servicesCount: 9,
  },
  {
    id: 'cat-caregiver',
    slug: 'caregiver',
    name: 'Caregiver & Nursing',
    nameBn: 'কেয়ারগিভার ও নার্সিং',
    description: 'Verified elderly care, post-surgery assistance, companion care & nursing.',
    iconName: 'Stethoscope',
    group: 'personal',
    servicesCount: 8,
  },
  {
    id: 'cat-vehicle',
    slug: 'vehicle-services',
    name: 'Vehicle Services',
    nameBn: 'গাড়ি ও বাইক সেবা',
    description: 'Car & bike mechanics, mobile car wash, professional drivers & emergency recovery.',
    iconName: 'Car',
    group: 'vehicle',
    servicesCount: 11,
  },
  {
    id: 'cat-marketplace',
    slug: 'marketplace',
    name: 'Local Marketplace',
    nameBn: 'পাড়ার দোকান ও বাজার',
    description: 'Local pharmacy, grocery, neighborhood restaurants & daily essentials delivered.',
    iconName: 'ShoppingBag',
    group: 'marketplace',
    servicesCount: 25,
  },
  {
    id: 'cat-rental',
    slug: 'rental',
    name: 'Rentals',
    nameBn: 'ভাড়া ও রেন্টাল',
    description: 'Apartments, family flats, cars, microbus, generators & event equipment.',
    iconName: 'Home',
    group: 'rental',
    servicesCount: 16,
  },
  {
    id: 'cat-emergency',
    slug: 'emergency',
    name: 'Emergency 24/7',
    nameBn: 'জরুরি সেবা ২৪/৭',
    description: 'Immediate 24/7 ambulance, roadside breakdown rescue & emergency tech dispatch.',
    iconName: 'AlertCircle',
    group: 'emergency',
    servicesCount: 6,
  },
];

export const MOCK_SERVICES: ServiceItem[] = [
  {
    id: 'srv-electrician',
    categoryId: 'cat-home',
    slug: 'electrician',
    name: 'Electrician & Wiring',
    nameBn: 'ইলেকট্রিশিয়ান ও ওয়্যারিং',
    description: 'Short circuit fix, switchboard installation, fan repair, circuit breaker maintenance.',
    startingPrice: 350,
    priceUnit: 'inspection starting from',
    durationEstimate: '1–2 hours',
    popular: true,
    icon: 'Zap',
  },
  {
    id: 'srv-plumber',
    categoryId: 'cat-home',
    slug: 'plumber',
    name: 'Plumbing & Sanitary Repair',
    nameBn: 'প্লাম্বিং ও পাইপলাইন মেরামত',
    description: 'Pipe leakage, commode & basin fixing, water pump installation, bathroom fittings.',
    startingPrice: 400,
    priceUnit: 'visit starting from',
    durationEstimate: '1–2 hours',
    popular: true,
    icon: 'Droplet',
  },
  {
    id: 'srv-ac',
    categoryId: 'cat-home',
    slug: 'ac-repair',
    name: 'AC Master Service & Gas Refill',
    nameBn: 'এসি সার্ভিস ও গ্যাস রিফিল',
    description: 'Deep jet wash cleaning, cooling issue resolution, freon gas top-up, compressor inspection.',
    startingPrice: 850,
    priceUnit: 'per unit',
    durationEstimate: '1.5 hours',
    popular: true,
    icon: 'Wind',
  },
  {
    id: 'srv-clean',
    categoryId: 'cat-home',
    slug: 'cleaning',
    name: 'Deep Home Cleaning',
    nameBn: 'বাড়ি ও কিচেন ডিপ ক্লিনিং',
    description: 'Complete floor scrubbing, kitchen chimney de-greasing, bathroom disinfection.',
    startingPrice: 1200,
    priceUnit: 'per room',
    durationEstimate: '3–4 hours',
    popular: true,
    icon: 'Sparkles',
  },
  {
    id: 'srv-panjabi',
    categoryId: 'cat-karigor',
    slug: 'custom-panjabi',
    name: 'Custom Panjabi Tailoring',
    nameBn: 'পাঞ্জাবি সেলাই ও কাটিং',
    description: 'Custom tailor-made semi-fitted, kabli or classic cotton panjabi with doorstep measurement.',
    startingPrice: 650,
    priceUnit: 'per piece',
    durationEstimate: '3–5 days',
    popular: true,
    icon: 'Scissors',
  },
  {
    id: 'srv-caregiver',
    categoryId: 'cat-caregiver',
    slug: 'elderly-care',
    name: 'Elderly Daily Assistance',
    nameBn: 'বয়োজ্যেষ্ঠ সেবা ও সঙ্গী',
    description: 'Assistance with mobility, medicine schedule, nutrition, companionship and doctor visits.',
    startingPrice: 1200,
    priceUnit: 'per 8-hr shift',
    durationEstimate: 'Daily/Monthly',
    popular: true,
    icon: 'HeartHandshake',
  },
  {
    id: 'srv-mechanic',
    categoryId: 'cat-vehicle',
    slug: 'car-wash',
    name: 'Doorstep Car Wash & Detailing',
    nameBn: 'বাসায় এসে গাড়ি ওয়াশ',
    description: 'Pressure foam wash, interior vacuuming, dashboard polish, tyre dressing right at your garage.',
    startingPrice: 600,
    priceUnit: 'per sedan',
    durationEstimate: '1 hour',
    popular: true,
    icon: 'Car',
  },
];

export const MOCK_PROVIDERS: ProviderProfile[] = [
  {
    id: 'prov-rafiq',
    userId: 'user-rafiq',
    user: {
      id: 'user-rafiq',
      fullName: 'Rafiqul Islam',
      phone: '01811111111',
      avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200',
      role: 'PROVIDER' as any,
      isVerified: true,
      createdAt: '2023-01-15',
      updatedAt: '2026-09-01',
    },
    headline: 'Certified Master Electrician (12+ Years)',
    bio: 'Government polytechnic certified with 12 years of hands-on experience in residential wiring, short-circuit diagnostics, safety DB box installation, and emergency power switches across Dhanmondi and surrounding areas.',
    experienceYears: 12,
    rating: 4.92,
    reviewCount: 148,
    verificationStatus: 'VERIFIED' as any,
    nidVerified: true,
    tradeLicenseVerified: true,
    serviceCategories: ['Home Services', 'Electrician'],
    serviceAreas: ['Dhanmondi', 'Lalmatia', 'Mohammadpur', 'Kalabagan'],
    basePrice: 400,
    isAvailableToday: true,
    location: { lat: 23.7465, lng: 90.3763, city: 'Dhaka', area: 'Dhanmondi' },
    portfolio: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    ],
    badges: ['NID Verified', 'Top Rated', 'Quick 30m Dispatch'],
    cancellationPolicy: 'Free cancellation up to 2 hours prior to scheduled appointment.',
    completedJobsCount: 312,
  },
  {
    id: 'prov-tanvir',
    userId: 'user-tanvir',
    user: {
      id: 'user-tanvir',
      fullName: 'Tanvir Ahmed',
      phone: '01822222222',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200',
      role: 'PROVIDER' as any,
      isVerified: true,
      createdAt: '2023-06-10',
      updatedAt: '2026-09-12',
    },
    headline: 'HVAC & Inverter AC Specialist',
    bio: 'Specialist in Daikin, General, Gree, and Walton inverter AC units. Offering precision pressure jet wash, gas leakage detection, electronic PCB repair, and compressor overhaul.',
    experienceYears: 8,
    rating: 4.88,
    reviewCount: 94,
    verificationStatus: 'VERIFIED' as any,
    nidVerified: true,
    tradeLicenseVerified: true,
    serviceCategories: ['Home Services', 'AC Repair'],
    serviceAreas: ['Gulshan 1', 'Gulshan 2', 'Banani', 'Baridhara', 'Badda'],
    basePrice: 850,
    isAvailableToday: true,
    location: { lat: 23.7925, lng: 90.4078, city: 'Dhaka', area: 'Gulshan 1' },
    portfolio: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500',
    ],
    badges: ['NID Verified', 'Cooling Pro', 'Original Parts'],
    cancellationPolicy: 'Free cancellation up to 3 hours prior.',
    completedJobsCount: 220,
  },
  {
    id: 'prov-jahangir',
    userId: 'user-jahangir',
    user: {
      id: 'user-jahangir',
      fullName: 'Master Jahangir Alam',
      phone: '01833333333',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
      role: 'PROVIDER' as any,
      isVerified: true,
      createdAt: '2022-03-20',
      updatedAt: '2026-09-20',
    },
    headline: 'Master Karigor & Bespoke Tailor',
    bio: 'Over 16 years of crafting executive formal suits, semi-fitted and classic panjabis, wedding sherwanis, and fine trousers. Doorstep measurement visits available across Dhaka.',
    experienceYears: 16,
    rating: 4.96,
    reviewCount: 210,
    verificationStatus: 'VERIFIED' as any,
    nidVerified: true,
    tradeLicenseVerified: true,
    serviceCategories: ['Karigor', 'Tailoring'],
    serviceAreas: ['Mirpur', 'Dhanmondi', 'Uttara', 'Mohammadpur'],
    basePrice: 650,
    isAvailableToday: true,
    location: { lat: 23.8041, lng: 90.3667, city: 'Dhaka', area: 'Mirpur' },
    portfolio: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500',
    ],
    badges: ['Master Artisan', 'Doorstep Measurement', 'Perfect Fit Guarantee'],
    cancellationPolicy: 'Measurements can be rescheduled without any charge.',
    completedJobsCount: 450,
  },
  {
    id: 'prov-sultana',
    userId: 'user-sultana',
    user: {
      id: 'user-sultana',
      fullName: 'Sultana Begum',
      phone: '01844444444',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200',
      role: 'PROVIDER' as any,
      isVerified: true,
      createdAt: '2023-09-01',
      updatedAt: '2026-09-28',
    },
    headline: 'Senior Certified Elderly & Patient Caregiver',
    bio: 'Diploma in Nursing and Geriatric Support. Dedicated to compassionate elderly care, mobility assistance, medication adherence, feeding tube support, and doctor visit accompaniment.',
    experienceYears: 7,
    rating: 4.95,
    reviewCount: 68,
    verificationStatus: 'VERIFIED' as any,
    nidVerified: true,
    tradeLicenseVerified: false,
    serviceCategories: ['Caregiver', 'Nursing'],
    serviceAreas: ['Dhanmondi', 'Mohammadpur', 'Lalmatia', 'Green Road'],
    basePrice: 1200,
    isAvailableToday: true,
    location: { lat: 23.7500, lng: 90.3700, city: 'Dhaka', area: 'Dhanmondi' },
    portfolio: [],
    badges: ['NID Verified', 'Nursing Diploma', 'Background Checked'],
    cancellationPolicy: 'Flexible cancellation before scheduled shift starts.',
    completedJobsCount: 110,
  },
];

export const MOCK_EMERGENCIES: EmergencyListing[] = [
  {
    id: 'em-1',
    name: 'Dhaka Central 24/7 ICU & AC Ambulance',
    serviceType: EmergencyServiceType.AMBULANCE,
    phone: '01711000999',
    altPhone: '029660000',
    operatingAreas: ['Dhanmondi', 'Mohammadpur', 'Shahbagh', 'Mirpur', 'Old Dhaka'],
    vehicleType: 'Type-C ICU Life Support Ambulance with Oxygen & Ventilator',
    isAvailable247: true,
    verifiedEmergencyProvider: true,
    etaMinutes: 12,
  },
  {
    id: 'em-2',
    name: 'Gulshan-Banani Express Emergency Ambulance',
    serviceType: EmergencyServiceType.AMBULANCE,
    phone: '01819222333',
    altPhone: '028881234',
    operatingAreas: ['Gulshan', 'Banani', 'Baridhara', 'Uttara', 'Bashundhara'],
    vehicleType: 'HiAce AC Cardiac & Trauma Support Ambulance',
    isAvailable247: true,
    verifiedEmergencyProvider: true,
    etaMinutes: 15,
  },
  {
    id: 'em-3',
    name: 'Padma Roadside Towing & Breakdown Rescue',
    serviceType: EmergencyServiceType.ROADSIDE_ASSISTANCE,
    phone: '01912333444',
    altPhone: '01711555666',
    operatingAreas: ['All Dhaka Metro', 'Dhaka-Chittagong Highway'],
    vehicleType: 'Hydraulic Flatbed Heavy Towing Truck & Battery Jumpstart Van',
    isAvailable247: true,
    verifiedEmergencyProvider: true,
    etaMinutes: 20,
  },
];

export const MOCK_RENTALS: RentalListing[] = [
  {
    id: 'rent-1',
    title: '3-BHK Modern Furnished Family Flat near Dhanmondi Lake',
    slug: '3-bhk-furnished-flat-dhanmondi-lake',
    type: RentalType.PROPERTY,
    ownerId: 'owner-1',
    ownerName: 'Syed Moazzem Hossain',
    location: 'Road 8A, Dhanmondi',
    city: 'Dhaka',
    pricePerMonth: 65000,
    pricePerDay: 3500,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    specs: { bedrooms: '3 Beds', bathrooms: '3 Baths', size: '1,850 sq ft', floor: '6th Floor', generator: '24/7 Full Backup' },
    description: 'Lakeside premium flat with south-facing balcony, round-the-clock security guards, dedicated car parking slot, and rooftop garden.',
    rules: ['Family preferred', 'Valid NID required', 'No loud midnight parties'],
    isAvailable: true,
    rating: 4.9,
  },
  {
    id: 'rent-2',
    title: 'Toyota Noah 7-Seater Family Microbus with Chauffeur',
    slug: 'toyota-noah-microbus-dhaka',
    type: RentalType.VEHICLE,
    ownerId: 'owner-2',
    ownerName: 'Mamunur Rashid',
    location: 'Mohakhali DOHS',
    city: 'Dhaka',
    pricePerDay: 4500,
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
    ],
    specs: { capacity: '7 Passengers', transmission: 'Automatic', ac: 'Dual Zone Climate Control', fuel: 'CNG + Octane' },
    description: 'Pristine condition family microbus suitable for wedding events, airport pickup/drop, or family vacation trips to Cox’s Bazar & Sylhet.',
    rules: ['Includes driver charge', 'Fuel/toll extra at cost', 'No smoking inside'],
    isAvailable: true,
    rating: 4.85,
  },
];

export const MOCK_BUSINESSES: BusinessProfile[] = [
  {
    id: 'biz-1',
    ownerId: 'owner-lazz',
    businessName: 'Lazz Pharma (Dhanmondi Branch)',
    slug: 'lazz-pharma-dhanmondi',
    category: 'PHARMACY',
    tradeLicenseNumber: 'TRAD/DNCC/021948',
    isVerified: true,
    address: 'Plot 32, Road 4, Dhanmondi',
    area: 'Dhanmondi',
    rating: 4.9,
    openingHours: '24 Hours Open',
    logoUrl: 'https://images.unsplash.com/photo-1586015555751-63c29994c6d3?w=200',
  },
];

export const MOCK_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-1',
    businessId: 'biz-1',
    name: 'Napa Extend 665mg (Box of 120 Tablets)',
    description: 'Paracetamol sustained release for long-lasting fever and body pain relief.',
    price: 240,
    inStock: true,
    stockCount: 50,
    category: 'Medicine',
    unit: 'box',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300',
  },
];

export const MOCK_ACTIVE_BOOKINGS: Booking[] = [
  {
    id: 'bk-101',
    trackingCode: 'PSB-2026-89412',
    customerId: 'demo-customer-1',
    providerId: 'prov-rafiq',
    provider: MOCK_PROVIDERS[0],
    serviceId: 'srv-electrician',
    service: MOCK_SERVICES[0],
    status: BookingStatus.PROVIDER_ON_THE_WAY,
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTimeSlot: '10:00 AM - 12:00 PM',
    address: 'House 42, Road 7A, Dhanmondi',
    area: 'Dhanmondi',
    notes: 'Main circuit breaker tripping repeatedly when 2 ACs are turned on.',
    totalAmount: 400,
    paymentMethod: PaymentMethod.CASH_ON_DELIVERY,
    paymentStatus: PaymentStatus.PENDING,
    statusHistory: [
      { status: BookingStatus.PENDING, timestamp: '10:00 AM', note: 'Booking requested by customer' },
      { status: BookingStatus.CONFIRMED, timestamp: '10:05 AM', note: 'Rafiqul Islam accepted your booking' },
      { status: BookingStatus.PROVIDER_ON_THE_WAY, timestamp: '10:20 AM', note: 'Provider is on the way (approx 15 mins)' },
    ],
    createdAt: '2026-10-01T10:00:00Z',
    updatedAt: '2026-10-01T10:20:00Z',
  },
];

export const MOCK_MEASUREMENTS: MeasurementProfile[] = [
  {
    id: 'ms-1',
    userId: 'demo-customer-1',
    profileName: 'Kamrul (Me)',
    gender: 'MALE',
    garmentType: 'Panjabi',
    measurements: {
      chest: 40,
      shoulder: 17.5,
      sleeve: 24,
      length: 42,
      collar: 15.5,
      cuff: 9.5,
    },
    notes: 'Semi-slim fit, mandarin collar, concealed front button placket.',
    createdAt: '2026-09-10',
    updatedAt: '2026-09-10',
  },
];

export const MOCK_TAILORING_ORDERS: TailoringOrder[] = [
  {
    id: 'to-1',
    orderNumber: 'KRG-2026-44129',
    customerId: 'demo-customer-1',
    tailorId: 'prov-jahangir',
    garmentType: 'Panjabi',
    measurementProfileId: 'ms-1',
    measurementVisitRequested: false,
    fabricSource: 'PROVIDED_BY_CUSTOMER',
    fabricDetails: 'Navy Blue Egyptian Giza Cotton fabric',
    currentStage: TailoringStage.STITCHING,
    estimatedDeliveryDate: '2026-10-06',
    totalPrice: 650,
    paymentStatus: PaymentStatus.PAID,
    statusHistory: [
      { stage: TailoringStage.MEASUREMENT, timestamp: 'Sep 29', note: 'Measurements verified from profile' },
      { stage: TailoringStage.FABRIC, timestamp: 'Sep 30', note: 'Fabric picked up from customer doorstep' },
      { stage: TailoringStage.CUTTING, timestamp: 'Oct 01', note: 'Pattern drafted and fabric cut' },
      { stage: TailoringStage.STITCHING, timestamp: 'Oct 01', note: 'Artisan stitching in progress' },
    ],
    createdAt: '2026-09-29',
  },
];
